#!/bin/bash

B="./res/build.edn"

COMMIT=`git rev-parse HEAD`
TS=`date --iso-8601=seconds`

read _ N V <<<`grep defproject project.clj`
V=${V%\"}
V=${V#\"}

echo ";; generated by build.sh" > $B
echo '{:name "'$N'" :version "'$V'" :commit "'$COMMIT'" :timestamp "'$TS'"}' >> $B

lein build

#.
