#!/bin/bash

PROD_HOST="www@ex1"
PROD_PATH="/www/main"
PROD_VAR="/www/main/var"
PROD_CONF="/www/conf/main.edn"

JAR="tmp/target/main.jar"

# ssh $PROD_HOST mkdir -p ${PROD_VAR}

chmod g+r $JAR
scp $JAR ${PROD_HOST}:${PROD_PATH}
# scp var/prod.edn ${PROD_HOST}:${PROD_CONF}
scp run stop ${PROD_HOST}:${PROD_PATH}
scp www-main.service ${PROD_HOST}:${PROD_PATH}

ssh $PROD_HOST $PROD_PATH/stop

#.
