#!/bin/bash

# anga@mph

PROD_HOST="anga"
PROD_PATH="/www/main"
PROD_VAR="/www/main/var"

JAR="tmp/target/main.jar"

#ssh $PROD_HOST mkdir -p ${PROD_VAR}

chmod g+r $JAR
scp $JAR ${PROD_HOST}:${PROD_PATH}
scp var/prod.edn ${PROD_HOST}:${PROD_VAR}/
scp run stop ${PROD_HOST}:${PROD_PATH}

ssh $PROD_HOST $PROD_PATH/stop

#.
