#!/bin/bash

PROD_HOST="app"
PROD_PATH="/app/main"
# PROD_CONF="/app/conf/main.edn"

JAR="tmp/angara-main.jar"

# PROD_VAR="/www/main/var"
# ssh $PROD_HOST mkdir -p ${PROD_VAR} 

chmod g+r $JAR
scp pm2.json run.sh $JAR ${PROD_HOST}:${PROD_PATH}

# scp ../conf/main.edn ${PROD_HOST}:${PROD_CONF}

ssh ${PROD_HOST} pm2 restart main

#.
